# Generated by Django 3.2.16 on 2023-02-01 05:13

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('preport', '0006_rename_cvss_base_score_db_finding_cvss_vector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', martor.models.MartorField()),
            ],
        ),
    ]
